##############################################################
# This file was automatically generated by UserHook system.
# Copy this file as ./userfunc.py
# And edit it.
# You can get results to expect. Lucks, K.Ogura.
##############################################################
import numpy as np
from pdb import *
from chainer.functions.connection.linear import linear
def save_params(_in,_out,_name):
    print(_in.link.__dict__['_params'])
    for k in _in.link.__dict__['_params']:
        filename = _name + '_' + k
        np.save(filename, _in.link.__dict__[k].data)
        _ = np.load(filename+'.npy') # To check

def lx1_Linear(_in,_out):
    _name="lx1_Linear"
    save_params(_in,_out,_name)
    pass

def ly2_Linear(_in,_out):
    _name="ly2_Linear"
    save_params(_in,_out,_name)
    pass

def lz3_Linear(_in,_out):
    _name="lz3_Linear"
    save_params(_in,_out,_name)
