##############################################################
# This file was automatically generated by UserHook system.
# Copy this file as ./userfunc.py
# And edit it.
# You can get results to expect. Lucks, K.Ogura.
##############################################################
import numpy as np
def conv1_Convolution2D(_in,_out):
    _name='conv1_Convolution2D'
    pass

def bn1_BatchNormalization(_in,_out):
    _name='bn1_BatchNormalization'
    pass

def conv2_Convolution2D(_in,_out):
    _name='conv2_Convolution2D'
    pass

def bn2_BatchNormalization(_in,_out):
    _name='bn2_BatchNormalization'
    pass

def l1_Linear(_in,_out):
    _name='l1_Linear'
    pass

def l2_Linear(_in,_out):
    _name='l2_Linear'
    pass

