##############################################################
# This file was automatically generated by UserHook system.
# Copy this file as ./userfunc.py
# And edit it.
# You can get results to expect. Lucks, K.Ogura.
##############################################################
import numpy as np
def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

def lx1_Linear(_in,_out):
    _name='lx1_Linear'
    pass

def ly2_Linear(_in,_out):
    _name='ly2_Linear'
    pass

def lz3_Linear(_in,_out):
    _name='lz3_Linear'
    pass

